@port = 3000

### USERS

### @name createUser
POST http://localhost:{{port}}/users
content-type: application/json

{
  "name": "John Doe",
  "email": "john@inter.net",
  "password": "teste123"
}

###

@userId = {{createUser.response.body.id}}

GET http://localhost:{{port}}/users/{{userId}}

###

PATCH http://localhost:{{port}}/users/{{userId}}
content-type: application/json

{
  "name": "João Zé",
  "email": "john@inter.net",
  "password": "teste123"
}

###

DELETE http://localhost:{{port}}/users/{{userId}}

### LANDLORDS

### @name createLandLord
POST http://localhost:{{port}}/landlords/{{userId}}
content-type: application/json

{ 
  "email": "john@inter.net",
  "companyName": "Doe Rentals",
  "companyDesc": "Empresa especializada em aluguel de imóveis residenciais.",
  "companyPassword": "empresa123"
}


### @name getLandLord
GET http://localhost:{{port}}/landlords/{{userId}}

### @name updateLandLord
PATCH http://localhost:{{port}}/landlords/{{userId}}
content-type: application/json

{
  "email": "john@inter.net",
  "companyName": "Doe Group",
  "companyDesc": "Atualização da descrição da empresa.",
  "companyPassword": "novaSenha456",
  "properties": []
}

### @name deleteLandLord
DELETE http://localhost:{{port}}/landlords/{{userId}}

### RENTAL-PLACES

### @name createRentalPlace
POST http://localhost:{{port}}/places
content-type: application/json

{
  "title": "Casa na praia",
  "description": "Vista para o mar, 3 quartos.",
  "address": "Avenida Atlântica, 456",
  "price": 3500,
  "available": true,
  "landLordId": "{{userId}}"
}

###

@placeId = {{createRentalPlace.response.body.id}}

###

GET http://localhost:{{port}}/places/{{placeId}}

###

PATCH http://localhost:{{port}}/places/{{placeId}}
content-type: application/json

{
    "title": "Casa na praia",
    "description": "Vista para o mar, 3 quartos.",
    "address": "Avenida Atlântica, 456",
    "price": 2700,
    "available": false,
    "landLordId": "{{userId}}"
}

###

DELETE http://localhost:{{port}}/places/{{placeId}}